services:
  node:
    image: node:16
    container_name: training_nodejs
    command: bash
    stdin_open: true
    tty: true
    restart: always
    ports:
    - 3000:3000
    volumes:
    - ./:/index
    working_dir: /index
    # networks:
    # - nodeapp


# As chaves `tty`, `stdin_open` e `command` fazem com que o container fique
# rodando em segundo plano, bem como tornam possível o uso do comando
# `docker attach`, já deixando o terminal atual acoplado ao container, direto
# no bash. Apesar disso, utilizar o attach mais de uma vez irá replicar o
# terminal, portanto é melhor utilizar o comando `docker exec`.

# A renomeação da rede padrão é feita pois caso contrário o nome da rede será
# o nome do diretório onde o arquivo atual se encontra, o que pode dificultar
# a listagem individual.